name:
services:
    cycle_count_coordinator:
        image:
        container_name:
        build:
            context: .
        ports:
            - '5000:80'
        environment:
            VERSION: 1.0.0
            MODE: debug
            SERVICE_NAME: service-name
            HTTP_PORT: 80
            MIGRATION_SOURCE: migrations
            JWT_SECRET: anything-secret

            # APM Configuration
            APM_SERVICE_NAME:
            APM_SERVER_URL:
            APM_SECRET_TOKEN:
            APM_ENVIRONMENT:

            # RabbitMQ
            RABBITMQ_URL:
            RMQ_RECONNECT_DELAY:
            RMQ_RETRY_INTERVAL:
            RMQ_QUEUE_PREFIX: service-dev

            # Read service DB
            READ_SERVICE_DB_HOST:
            READ_SERVICE_DB_PORT:
            READ_SERVICE_DB_NAME:
            READ_SERVICE_DB_USER:
            READ_SERVICE_DB_PASSWORD:
            READ_SERVICE_DB_MAX_IDLE_TIME_IN_MINUTES:
            READ_SERVICE_DB_MAX_OPEN_CONNS:
            READ_SERVICE_DB_MAX_IDLE_CONNS:
            READ_SERVICE_DB_ENABLE_SSL_MODE:

            # Write DB
            WRITE_SERVICE_DB_HOST:
            WRITE_SERVICE_DB_PORT:
            WRITE_SERVICE_DB_NAME:
            WRITE_SERVICE_DB_USER:
            WRITE_SERVICE_DB_PASSWORD:
            WRITE_SERVICE_DB_MAX_IDLE_TIME_IN_MINUTES:
            WRITE_SERVICE_DB_MAX_OPEN_CONNS:
            WRITE_SERVICE_DB_MAX_IDLE_CONNS:
            WRITE_SERVICE_DB_ENABLE_SSL_MODE:
