name: Feature Request
description: Suggest a new feature for the gw2style MVP
title: '[Feature] gw2style - '
labels: ['enhancement', 'mvp']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for gw2style! Please provide clear details to help us prioritize and implement it.
  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      placeholder: e.g., "Web app for uploading and browsing outfits"
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature and why it’s needed.
      placeholder: |
        What does this feature do? e.g., "Web app for uploading and browsing outfits"
        Why is it needed? e.g., "No central platform for GW2 outfit sharing"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this feature for the MVP?
      options:
        - Must-Have (v0.1)
        - Should-Have (Post-MVP)
        - Could-Have (Nice-to-Have)
        - Won't-Have (Out of Scope)
      default: 2
    validations:
      required: true